# #############################################################################
# Host/Hardware Setup
#
# Hardware: a virtual root server at Netcup

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/profiles/qemu-guest.nix") ];

  #############################################################################
  # Filesystem Setup
  #

  # 1. Setup the disk:
  #
  # # Create an MSDOS disk
  # parted /dev/vda -- mklabel msdos
  #
  # # Create the main disk. Leavew 1Meg of space for for grub/mbr stuff
  # # Leave 16GB at the end as swap space
  # parted /dev/vda -- mkpart primary 1MiB -16GiB
  #
  # # Create a swap disk
  # parted /dev/vda -- mkpart primary linux-swap -16GiB 100%
  #
  # 2. Format disks
  # ATTENTION: this config uses labels for disks. Ensure you use these labels.
  #
  # mkfs.ext4 -L nixos /dev/vda1
  # mkswap -L swap /dev/vda2

  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  swapDevices = [{ device = "/dev/disk/by-label/swap"; }];

  #############################################################################
  # Kernel and initrd Setup
  #

  # Generated by nixos-generate-config --root /mnt
  boot.initrd.availableKernelModules =
    [ "ata_piix" "uhci_hcd" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  #############################################################################
  # Boot Setup
  #

  # these machines emulate bios boot.
  boot.loader.grub.enable = true;
  boot.loader.grub.device = "/dev/vda";
}
